name: Teams
version: 1.0.0.a
api-version: 1.16
author: bk and CrimsonDart
main: net.pgfmc.teams.Main
description: implemets the Teams system
commands:
   team:
      usage: /team
      permission: Teams.team
      description: Opens the team inventory.
   teamRequest:
      usage: /teamRequest <Player>
      aliases: [TR]
      permission: Teams.teamRequest
      description: invites or sends a request to Player <Player>.
   teamAccept:
      usage: teamAccept
      aliases: [TA]
      permission: Teams.teamAccept
      description: Accepts the invite / request sent in teamRequest.
   vote:
      usage: /vote
      aliases: [V]
      permission: Teams.vote
      description: Opens the Vote inventory.
   voteKick:
      usage: /voteKick <Teamate>
      aliases: [VK]
      permission: Teams.voteKick
      description: Opens a vote to Kick <Teamate> from your team.
   voteBan:
      usage: /voteBan <Teamate>
      aliases: [VB]
      permission: Teams.voteBan
      description: Opens a vote to Ban <Teamate> from your team.
   voteAllyRequest:
      usage: /voteAllyRequest <other Team>
      aliases: [VAR]
      permission: Teams.voteAllyRequest
      description: Opens a vote to send an ally request to another team.
   voteRenameTeam:
      usage: /voteRenameTeam <new Team name>
      aliases: [VRT, renameTeam, voteRename,]
      permission: Teams.voterename
      description: Opens a vote to Rename your team to <new Team name>