name: Teams
version: 1.2.3.b
api-version: 1.16
author: [bk, CrimsonDart]
main: net.pgfmc.teams.teamscore.TeamsCore
description: implemets the Teams system
depend: [Multiverse-Core, PGF-Essentials]
commands:
   inspector:
      usage: /inspector while in Creative Mode.
      aliases: [insp]
      permission: Teams.inspecotor
      description: toggles inspector mode, which uncovers data about blocks.
   debug:
      usage: /debug
      permission: Teams.debug
      description: toggles debug mode, which floods the console with text lol
   containerDump:
      usage: /containerDump
      permission: Teams.dump
      description: dumps all container data into the console, for debug purposes.
   friendRequest:
      aliases: [fr]
      usage: /<command> <player>
      permission: Teams.friend
      description: sends a friend request to <player>.
   friendAccept:
      aliases: [fa]
      usage: /<command>
      permission: Teams.friend
      description: accepts a friend request.
#
# -------------------------------||------------------------------
#
#PlayerData entries used in Teams:

