name: Teams
version: 1.2.2.b
api-version: 1.16
author: bk and CrimsonDart
main: net.pgfmc.teams.teamscore.TeamsCore
description: implemets the Teams system
depend: [Multiverse-Core, PGF-Essentials]
commands:
   team:
      usage: /team
      permission: Teams.team
      description: Opens the team inventory.
   Invite:
      usage: /Invite <Player>
      aliases: [invite, i]
      permission: Teams.teamRequest
      description: invites or sends a request to Player <Player>.
   teamAccept:
      usage: teamAccept
      aliases: [teamaccept, tma]
      permission: Teams.teamAccept
      description: Accepts the invite / request sent in teamRequest.
#   vote:
#      usage: /vote
#      aliases: [vote, V]
#      permission: Teams.vote
#      description: Opens the Vote inventory.
#  voteKick:
#      usage: /voteKick <Teamate>
#      aliases: [voteKick, votekick, VK]
#      permission: Teams.voteKick
#      description: Opens a vote to Kick <Teamate> from your team.
#   voteBan:
#      usage: /voteBan <Teamate>
#      aliases: [voteBan, voteban, VB]
#      permission: Teams.voteBan
#      description: Opens a vote to Ban <Teamate> from your team.
#   voteAllyRequest:
#      usage: /voteAllyRequest <other Team>
#      aliases: [voteAllyRequest, voteallyrequest, VAR]
#      permission: Teams.voteAllyRequest
#      description: Opens a vote to send an ally request to another team.
#   voteRenameTeam:
#      usage: /voteRenameTeam <new Team name>
#      aliases: [VRT, renameTeam, voteRename]
#      permission: Teams.voterename
#      description: Opens a vote to Rename your team to <new Team name>
   leaveTeam:
      usage: /leaveTeam
      aliases: [leaveTeam, leaveteam, lt]
      permission: Teams.leave
      description: sends the sender a confirmation message, asking if they are sure that they want to leave their team.
   leaveTeamConfirm:
      usage: /leaveTeamConfirm
      aliases: [leaveTeamConfirm, leaveteamconfirm, ltc]
      permission: Teams.leaveConfirm
      description: makes the sender leave their own team.
#   inspector:
#      usage: /inspector while in Creative Mode.
#      aliases: [insp, INSP]
#      permission: Teams.inspecotor
#      description: toggles inspector mode, which uncovers data about blocks.