name: Teams
version: 1.2.3.b
api-version: 1.16
author: [bk, CrimsonDart]
main: net.pgfmc.teams.teamscore.TeamsCore
description: implemets the Teams system
depend: [Multiverse-Core, PGF-Essentials]
commands:
   team:
      usage: /team
      permission: Teams.team
      description: Opens the team inventory.
   Invite:
      usage: /Invite <Player>
      aliases: [i]
      permission: Teams.teamRequest
      description: invites or sends a request to Player <Player>.
   teamAccept:
      usage: teamAccept
      aliases: [tma]
      permission: Teams.teamAccept
      description: Accepts the invite / request sent in teamRequest.
   leaveTeam:
      usage: /leaveTeam
      aliases: [lt]
      permission: Teams.leave
      description: sends the sender a confirmation message, asking if they are sure that they want to leave their team.
   leaveTeamConfirm:
      usage: /leaveTeamConfirm
      aliases: [ltc]
      permission: Teams.leaveConfirm
      description: makes the sender leave their own team.
   inspector:
      usage: /inspector while in Creative Mode.
      aliases: [insp]
      permission: Teams.inspecotor
      description: toggles inspector mode, which uncovers data about blocks.
   debug:
      usage: /debug
      permission: Teams.debug
      description: toggles debug mode, which floods the console with text lol
   containerDump:
      usage: /containerDump
      permission: Teams.dump
      description: dumps all container data into the console, for debug purposes.
#
# -------------------------------||------------------------------
#
#PlayerData entries used in Teams:

