name: Teams
version: 4.0.2
api-version: 1.18
author: [bk, CrimsonDart]
main: net.pgfmc.teams.Main
description: implemets the Teams system
depend: [PGF-Core]
commands:
   friendRequest:
      aliases: [fr]
      usage: /<command> <player>
      permission: teams.friend.request
      description: sends a friend request to <player>.
   friendAccept:
      aliases: [fa]
      usage: /<command>
      permission: teams.friend.accept
      description: accepts a friend request.
   unfriend:
      aliases: [uf]
      usage: /<command> <friend>
      permission: teams.friend.unfriend
      description: unfriends <player>
   friendlist:
      aliases: [flist]
      usage: /<command>
      permission: teams.friend.list
      description: shows friends list.
   favorite:
      aliases: [fav]
      usage: /<command> <friend>
      permission: teams.friend.fav
      description: favorites a friend.
   unfavorite: 
      aliases: [unfav]
      usage: /<command> <favorite>
      permission: teams.friend.unfav
      description: unfavorites a friend.
   inspector:
      aliases: [insp]
      usage: /<command>
      permission: teams.inspector
      description: toggles Inspector mode if in Creative mode.
   
#
# -------------------------------||------------------------------
#
#PlayerData entries used in Teams:

